DATASET:
  TRAIN_FILE_LIST: /CustomDataset/processed_images/train.txt
  EVAL_FILE_LIST: /CustomDataset/processed_images/val.txt
  TRAIN_BATCH_SIZE: 64
  EVAL_BATCH_SIZE: 1
  EXP: True
  EXP_DIM: 64
  FRAME_LEN: 1
  COEFF_LEN: 73
  NUM_CLASSES: 46
  AUDIO_ROOT_PATH: /apdcephfs_cq2/share_1290939/wenxuazhang/voxceleb1/wav
  DEBUG: True
  

MODEL:
  AUDIOENCODER:
    LEAKY_RELU: True
    NORM: 'IN'
  DISCRIMINATOR:
    LEAKY_RELU: False
    INPUT_CHANNELS: 6
  CVAE:
    AUDIO_EMB_IN_SIZE: 512
    AUDIO_EMB_OUT_SIZE: 6
    SEQ_LEN: 32
    LATENT_SIZE: 64
    ENCODER_LAYER_SIZES: [192, 128]
    DECODER_LAYER_SIZES: [128, 192]
    

TRAIN:
  MAX_EPOCH: 100
  GENERATOR:
    LR: 1.0e-4
  DISCRIMINATOR:
    LR: 1.0e-4
  LOSS:
    LAMBDA_REG: 1
    LAMBDA_LANDMARKS: 0
    LAMBDA_VERTICES: 0
    LAMBDA_GAN_MOTION: 0.7
    LAMBDA_GAN_COEFF: 0
    LAMBDA_KL: 1

TAG:
  NAME: small_dataset_with_one_audio


